import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Ring

/-!
# CNRS Problem 2, Layer P2-L1: branch-cover coordinates

This module formalizes the quotient-coordinate content of the governed
Problem 2 sources.  A raw coordinate `(r, theta, k)` has positive radius and
total angle `theta + 2*pi*k`.  Two raw coordinates describe the same point of
the universal cover exactly when their radii and total angles agree.

The canonical carrier `BranchPoint` stores precisely those two invariants.
The development deliberately does not yet formalize CNRS-A digit strings,
branch serialization, addition, or the CNRS-H differential extension.
-/

namespace CNRSProblem2

noncomputable section

/-- A redundant Problem 2 coordinate `(r, theta, k)`. -/
structure RawBranchCoord where
  radius : ℝ
  radius_pos : 0 < radius
  angle : ℝ
  branch : ℤ

@[ext] theorem RawBranchCoord.ext {x y : RawBranchCoord}
    (hr : x.radius = y.radius) (ha : x.angle = y.angle)
    (hk : x.branch = y.branch) : x = y := by
  cases x
  cases y
  simp_all

/-- The invariant total angle of a redundant coordinate. -/
def RawBranchCoord.totalAngle (x : RawBranchCoord) : ℝ :=
  x.angle + 2 * Real.pi * (x.branch : ℝ)

/-- Coordinate equivalence from the Problem 2 quotient presentation. -/
def CoordEquivalent (x y : RawBranchCoord) : Prop :=
  x.radius = y.radius ∧ x.totalAngle = y.totalAngle

theorem coordEquivalent_refl (x : RawBranchCoord) : CoordEquivalent x x :=
  ⟨rfl, rfl⟩

theorem coordEquivalent_symm {x y : RawBranchCoord}
    (h : CoordEquivalent x y) : CoordEquivalent y x :=
  ⟨h.1.symm, h.2.symm⟩

theorem coordEquivalent_trans {x y z : RawBranchCoord}
    (hxy : CoordEquivalent x y) (hyz : CoordEquivalent y z) :
    CoordEquivalent x z :=
  ⟨hxy.1.trans hyz.1, hxy.2.trans hyz.2⟩

/-- Shift `theta` by a whole turn and compensate in the branch index. -/
def RawBranchCoord.reindex (x : RawBranchCoord) (n : ℤ) : RawBranchCoord where
  radius := x.radius
  radius_pos := x.radius_pos
  angle := x.angle + 2 * Real.pi * (n : ℝ)
  branch := x.branch - n

@[simp] theorem RawBranchCoord.totalAngle_reindex
    (x : RawBranchCoord) (n : ℤ) :
    (x.reindex n).totalAngle = x.totalAngle := by
  simp [RawBranchCoord.reindex, RawBranchCoord.totalAngle]
  ring

theorem RawBranchCoord.reindex_equivalent
    (x : RawBranchCoord) (n : ℤ) : CoordEquivalent (x.reindex n) x := by
  exact ⟨rfl, x.totalAngle_reindex n⟩

/-- The invariant-based relation is exactly the relation generated by the
governed whole-turn reindexing `(r, theta, k) ~ (r, theta + 2*pi, k - 1)`. -/
theorem coordEquivalent_iff_exists_reindex (x y : RawBranchCoord) :
    CoordEquivalent x y ↔ ∃ n : ℤ, x.reindex n = y := by
  constructor
  · rintro ⟨hr, ha⟩
    refine ⟨x.branch - y.branch, ?_⟩
    apply RawBranchCoord.ext
    · exact hr
    · dsimp [RawBranchCoord.reindex]
      dsimp [RawBranchCoord.totalAngle] at ha
      push_cast
      linear_combination ha
    · dsimp [RawBranchCoord.reindex]
      omega
  · rintro ⟨n, rfl⟩
    exact coordEquivalent_symm (x.reindex_equivalent n)

/-- The nonredundant universal-cover carrier `(positive radius, total angle)`. -/
structure BranchPoint where
  radius : ℝ
  radius_pos : 0 < radius
  totalAngle : ℝ

@[ext] theorem BranchPoint.ext {x y : BranchPoint}
    (hr : x.radius = y.radius) (ha : x.totalAngle = y.totalAngle) : x = y := by
  cases x
  cases y
  simp_all

/-- Forget redundant `(theta,k)` coordinates while preserving total angle. -/
def RawBranchCoord.toBranchPoint (x : RawBranchCoord) : BranchPoint where
  radius := x.radius
  radius_pos := x.radius_pos
  totalAngle := x.totalAngle

theorem RawBranchCoord.toBranchPoint_eq_iff (x y : RawBranchCoord) :
    x.toBranchPoint = y.toBranchPoint ↔ CoordEquivalent x y := by
  constructor
  · intro h
    exact ⟨congrArg BranchPoint.radius h, congrArg BranchPoint.totalAngle h⟩
  · rintro ⟨hr, ha⟩
    cases x
    cases y
    simp_all [RawBranchCoord.toBranchPoint]

/-- Every branch point has a raw representative, with branch index zero. -/
def BranchPoint.rawRepresentative (x : BranchPoint) : RawBranchCoord where
  radius := x.radius
  radius_pos := x.radius_pos
  angle := x.totalAngle
  branch := 0

@[simp] theorem BranchPoint.rawRepresentative_toBranchPoint (x : BranchPoint) :
    x.rawRepresentative.toBranchPoint = x := by
  apply BranchPoint.ext <;>
    simp [BranchPoint.rawRepresentative, RawBranchCoord.toBranchPoint,
      RawBranchCoord.totalAngle]

theorem RawBranchCoord.toBranchPoint_surjective :
    Function.Surjective RawBranchCoord.toBranchPoint := by
  intro x
  exact ⟨x.rawRepresentative, x.rawRepresentative_toBranchPoint⟩

/-- Multiplication before quotienting: multiply radii and add both angles and indices. -/
def RawBranchCoord.mul (x y : RawBranchCoord) : RawBranchCoord where
  radius := x.radius * y.radius
  radius_pos := mul_pos x.radius_pos y.radius_pos
  angle := x.angle + y.angle
  branch := x.branch + y.branch

@[simp] theorem RawBranchCoord.totalAngle_mul (x y : RawBranchCoord) :
    (x.mul y).totalAngle = x.totalAngle + y.totalAngle := by
  simp [RawBranchCoord.mul, RawBranchCoord.totalAngle]
  ring

theorem CoordEquivalent.mul {x x' y y' : RawBranchCoord}
    (hx : CoordEquivalent x x') (hy : CoordEquivalent y y') :
    CoordEquivalent (x.mul y) (x'.mul y') := by
  constructor
  · exact congrArg₂ (· * ·) hx.1 hy.1
  · simp only [RawBranchCoord.totalAngle_mul]
    rw [hx.2, hy.2]

/-- Multiplication on the nonredundant branch cover. -/
def BranchPoint.mul (x y : BranchPoint) : BranchPoint where
  radius := x.radius * y.radius
  radius_pos := mul_pos x.radius_pos y.radius_pos
  totalAngle := x.totalAngle + y.totalAngle

/-- Multiplicative identity of the branch cover. -/
def BranchPoint.one : BranchPoint where
  radius := 1
  radius_pos := zero_lt_one
  totalAngle := 0

/-- Multiplicative inverse on the branch cover. -/
def BranchPoint.inv (x : BranchPoint) : BranchPoint where
  radius := x.radius⁻¹
  radius_pos := inv_pos.mpr x.radius_pos
  totalAngle := -x.totalAngle

@[simp] theorem RawBranchCoord.toBranchPoint_mul (x y : RawBranchCoord) :
    (x.mul y).toBranchPoint = x.toBranchPoint.mul y.toBranchPoint := by
  cases x
  cases y
  simp [RawBranchCoord.mul, RawBranchCoord.toBranchPoint,
    RawBranchCoord.totalAngle, BranchPoint.mul]
  ring

theorem BranchPoint.mul_assoc (x y z : BranchPoint) :
    (x.mul y).mul z = x.mul (y.mul z) := by
  apply BranchPoint.ext
  · exact _root_.mul_assoc x.radius y.radius z.radius
  · exact add_assoc x.totalAngle y.totalAngle z.totalAngle

theorem BranchPoint.mul_comm (x y : BranchPoint) : x.mul y = y.mul x := by
  apply BranchPoint.ext
  · exact _root_.mul_comm x.radius y.radius
  · exact add_comm x.totalAngle y.totalAngle

theorem BranchPoint.one_mul (x : BranchPoint) : BranchPoint.one.mul x = x := by
  apply BranchPoint.ext <;> simp [BranchPoint.one, BranchPoint.mul]

theorem BranchPoint.mul_one (x : BranchPoint) : x.mul BranchPoint.one = x := by
  rw [BranchPoint.mul_comm]
  exact x.one_mul

theorem BranchPoint.mul_inv (x : BranchPoint) : x.mul x.inv = BranchPoint.one := by
  apply BranchPoint.ext
  · simp [BranchPoint.mul, BranchPoint.inv, BranchPoint.one, ne_of_gt x.radius_pos]
  · simp [BranchPoint.mul, BranchPoint.inv, BranchPoint.one]

theorem BranchPoint.inv_mul (x : BranchPoint) : x.inv.mul x = BranchPoint.one := by
  rw [BranchPoint.mul_comm]
  exact x.mul_inv

/-- The branch cover is exactly the product of positive radius and total angle. -/
def BranchPoint.dataEquiv : BranchPoint ≃ {r : ℝ // 0 < r} × ℝ where
  toFun x := ⟨⟨x.radius, x.radius_pos⟩, x.totalAngle⟩
  invFun x := ⟨x.1.1, x.1.2, x.2⟩
  left_inv x := by cases x; rfl
  right_inv x := by cases x; rfl

end

end CNRSProblem2
