import CNRSProblem1.FullRealization
import CNRSProblem1.Periodicity

namespace CNRSProblem1

noncomputable section

/-- The value of an integral coordinate pair in the fixed-denominator
quadratic lattice generated by `1` and `alpha`. -/
def quadraticLatticeValue (alpha : ℝ) (q : ℕ) (v : ℤ × ℤ) : ℝ :=
  ((v.1 : ℝ) + (v.2 : ℝ) * alpha) / q

/-- Integral coordinate update induced by `x ↦ -beta*x-d` when
`beta^2-trace*beta+norm=0`. -/
def quadraticLatticeStep (trace norm : ℤ) (q : ℕ)
    (v : ℤ × ℤ) (d : ℤ) : ℤ × ℤ :=
  (v.2 * norm - d * q, -v.1 - v.2 * trace)

/-- Explicit quadratic data sufficient for the lattice-finiteness argument. -/
structure QuadraticLatticeData where
  beta : ℝ
  conjugate : ℝ
  trace : ℤ
  norm : ℤ
  beta_mem : (2 : ℝ) < beta ∧ beta < 3
  conjugate_abs_lt_one : |conjugate| < 1
  beta_ne_conjugate : beta ≠ conjugate
  beta_polynomial : beta ^ 2 - (trace : ℝ) * beta + norm = 0
  conjugate_polynomial :
    conjugate ^ 2 - (trace : ℝ) * conjugate + norm = 0

theorem quadraticLatticeValue_step
    (alpha : ℝ) (trace norm : ℤ) (q : ℕ) (hq : 0 < q)
    (hpoly : alpha ^ 2 - (trace : ℝ) * alpha + norm = 0)
    (v : ℤ × ℤ) (d : ℤ) :
    quadraticLatticeValue alpha q
        (quadraticLatticeStep trace norm q v d) =
      -alpha * quadraticLatticeValue alpha q v - d := by
  have hq0 : (q : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hq)
  unfold quadraticLatticeValue quadraticLatticeStep
  simp only
  push_cast
  field_simp [hq0]
  linear_combination (v.2 : ℝ) * hpoly

/-- The integral coordinates of the orbit, with denominator fixed at `q`. -/
def quadraticLatticeCoords (D : QuadraticLatticeData) (q : ℕ)
    (v : ℤ × ℤ) : ℕ → ℤ × ℤ
  | 0 => v
  | n + 1 =>
      quadraticLatticeStep D.trace D.norm q (quadraticLatticeCoords D q v n)
        (orbitDigit D.beta (quadraticLatticeValue D.beta q v) n)

@[simp] theorem quadraticLatticeCoords_zero
    (D : QuadraticLatticeData) (q : ℕ) (v : ℤ × ℤ) :
    quadraticLatticeCoords D q v 0 = v := rfl

@[simp] theorem quadraticLatticeCoords_succ
    (D : QuadraticLatticeData) (q : ℕ) (v : ℤ × ℤ) (n : ℕ) :
    quadraticLatticeCoords D q v (n + 1) =
      quadraticLatticeStep D.trace D.norm q (quadraticLatticeCoords D q v n)
        (orbitDigit D.beta (quadraticLatticeValue D.beta q v) n) := rfl

/-- Every real orbit state retains the original denominator and integral
quadratic coordinates. -/
theorem quadraticLatticeCoords_beta_value
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ) :
    ∀ n, quadraticLatticeValue D.beta q (quadraticLatticeCoords D q v n) =
      orbit D.beta (quadraticLatticeValue D.beta q v) n := by
  intro n
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [quadraticLatticeCoords_succ,
        quadraticLatticeValue_step D.beta D.trace D.norm q hq
          D.beta_polynomial]
      rw [ih]
      rfl

/-- Applying the second real embedding to the same integral coordinates gives
the contracted conjugate recurrence driven by the actual orbit digits. -/
theorem quadraticLatticeCoords_conjugate_value
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ) :
    ∀ n, quadraticLatticeValue D.conjugate q
        (quadraticLatticeCoords D q v n) =
      conjugateOrbit D.conjugate
        (quadraticLatticeValue D.conjugate q v)
        (orbitStream D.beta (quadraticLatticeValue D.beta q v)) n := by
  intro n
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [quadraticLatticeCoords_succ,
        quadraticLatticeValue_step D.conjugate D.trace D.norm q hq
          D.conjugate_polynomial]
      rw [ih]
      rfl

theorem fundamentalInterval_abs_lt_one
    {beta x : ℝ} (hbeta : 1 < beta) (hx : InFundamentalInterval beta x) :
    |x| < 1 := by
  have hpos : 0 < beta + 1 := beta_add_one_pos hbeta
  have hl : (-1 : ℝ) < leftEndpoint beta := by
    unfold leftEndpoint
    rw [lt_div_iff₀ hpos]
    linarith
  have hr : rightEndpoint beta < 1 := by
    unfold rightEndpoint
    rw [div_lt_iff₀ hpos]
    linarith
  rw [abs_lt]
  exact ⟨lt_of_lt_of_le hl hx.1, lt_trans hx.2 hr⟩

theorem target_orbitDigit_abs_le_two
    (D : QuadraticLatticeData) {x : ℝ}
    (hx : InFundamentalInterval D.beta x) (n : ℕ) :
    |(orbitDigit D.beta x n : ℝ)| ≤ 2 := by
  have hbeta : 1 < D.beta := lt_trans (by norm_num) D.beta_mem.1
  have hd := digit_mem_alphabet hbeta (orbit_mem hbeta hx n)
  have hfloor : ⌊D.beta⌋ = 2 := by
    rw [Int.floor_eq_iff]
    constructor
    · exact_mod_cast D.beta_mem.1.le
    · norm_num
      exact D.beta_mem.2
  rw [hfloor] at hd
  have hz : (-2 : ℤ) ≤ digit D.beta (orbit D.beta x n) ∧
      digit D.beta (orbit D.beta x n) ≤ 2 := by omega
  change |(digit D.beta (orbit D.beta x n) : ℝ)| ≤ 2
  rw [abs_le]
  exact_mod_cast hz

/-- A convenient invariant bound for the conjugate coordinate. -/
def quadraticConjugateBound (D : QuadraticLatticeData) (q : ℕ)
    (v : ℤ × ℤ) : ℝ :=
  max |quadraticLatticeValue D.conjugate q v|
    (2 / (1 - |D.conjugate|))

theorem quadraticConjugateBound_spec
    (D : QuadraticLatticeData) (q : ℕ) (v : ℤ × ℤ) :
    |quadraticLatticeValue D.conjugate q v| ≤
        quadraticConjugateBound D q v ∧
      2 ≤ (1 - |D.conjugate|) * quadraticConjugateBound D q v := by
  have hden : 0 < 1 - |D.conjugate| := by
    linarith [D.conjugate_abs_lt_one]
  constructor
  · exact le_max_left _ _
  · have h := le_max_right
        |quadraticLatticeValue D.conjugate q v|
        (2 / (1 - |D.conjugate|))
    have h' := (div_le_iff₀ hden).mp h
    simpa [quadraticConjugateBound, mul_comm] using h'

theorem quadraticLatticeCoords_conjugate_bound
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval D.beta
      (quadraticLatticeValue D.beta q v)) :
    ∀ n, |quadraticLatticeValue D.conjugate q
        (quadraticLatticeCoords D q v n)| ≤
      quadraticConjugateBound D q v := by
  have hdigits : ∀ n,
      |(orbitStream D.beta (quadraticLatticeValue D.beta q v) n : ℝ)| ≤ 2 := by
    intro n
    exact target_orbitDigit_abs_le_two D hx n
  have hbound := quadraticConjugateBound_spec D q v
  intro n
  rw [quadraticLatticeCoords_conjugate_value D hq v n]
  exact conjugateOrbit_invariant_bound hdigits hbound.2 hbound.1 n

theorem quadraticLattice_coordinate_bounds
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval D.beta
      (quadraticLatticeValue D.beta q v)) :
    ∃ A B : ℝ, ∀ n,
      |((quadraticLatticeCoords D q v n).1 : ℝ)| ≤ A ∧
      |((quadraticLatticeCoords D q v n).2 : ℝ)| ≤ B := by
  let C := quadraticConjugateBound D q v
  let B := (q : ℝ) * (1 + C) / |D.beta - D.conjugate|
  let A := (q : ℝ) + B * |D.beta|
  refine ⟨A, B, ?_⟩
  intro n
  let w := quadraticLatticeCoords D q v n
  let y := quadraticLatticeValue D.beta q w
  let z := quadraticLatticeValue D.conjugate q w
  have hbeta : 1 < D.beta := lt_trans (by norm_num) D.beta_mem.1
  have hylt : |y| < 1 := by
    unfold y w
    rw [quadraticLatticeCoords_beta_value D hq v n]
    exact fundamentalInterval_abs_lt_one hbeta (orbit_mem hbeta hx n)
  have hy : |y| ≤ 1 := hylt.le
  have hz : |z| ≤ C := by
    exact quadraticLatticeCoords_conjugate_bound D hq v hx n
  have hsep : 0 < |D.beta - D.conjugate| :=
    abs_pos.mpr (sub_ne_zero.mpr D.beta_ne_conjugate)
  have hqreal : 0 ≤ (q : ℝ) := by positivity
  have hrel : (q : ℝ) * (y - z) =
      (w.2 : ℝ) * (D.beta - D.conjugate) := by
    unfold y z quadraticLatticeValue
    have hq0 : (q : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hq)
    field_simp [hq0]
    ring
  have hbmul : |(w.2 : ℝ)| * |D.beta - D.conjugate| ≤
      (q : ℝ) * (1 + C) := by
    rw [← abs_mul, ← hrel, abs_mul]
    calc
      |(q : ℝ)| * |y - z| ≤ (q : ℝ) * (|y| + |z|) := by
        rw [abs_of_nonneg hqreal]
        gcongr
        exact abs_sub y z
      _ ≤ (q : ℝ) * (1 + C) := by gcongr
  have hb : |(w.2 : ℝ)| ≤ B := by
    unfold B
    exact (le_div_iff₀ hsep).2 hbmul
  have harel : (w.1 : ℝ) = (q : ℝ) * y - (w.2 : ℝ) * D.beta := by
    unfold y quadraticLatticeValue
    have hq0 : (q : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hq)
    field_simp [hq0]
    ring
  constructor
  · rw [harel]
    calc
      |(q : ℝ) * y - (w.2 : ℝ) * D.beta| ≤
          |(q : ℝ) * y| + |(w.2 : ℝ) * D.beta| := abs_sub _ _
      _ = (q : ℝ) * |y| + |(w.2 : ℝ)| * |D.beta| := by
        rw [abs_mul, abs_mul, abs_of_nonneg hqreal]
      _ ≤ (q : ℝ) * 1 + B * |D.beta| :=
        add_le_add (mul_le_mul_of_nonneg_left hy hqreal)
          (mul_le_mul_of_nonneg_right hb (abs_nonneg D.beta))
      _ = (q : ℝ) + B * |D.beta| := by ring
      _ = A := rfl
  · exact hb

theorem quadraticLatticeCoords_finite_range
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval D.beta
      (quadraticLatticeValue D.beta q v)) :
    (Set.range (quadraticLatticeCoords D q v)).Finite := by
  obtain ⟨A, B, hbounds⟩ := quadraticLattice_coordinate_bounds D hq v hx
  obtain ⟨K, hK⟩ := exists_nat_ge (max A B)
  let box : Set (ℤ × ℤ) :=
    Set.Icc (-(K : ℤ)) (K : ℤ) ×ˢ Set.Icc (-(K : ℤ)) (K : ℤ)
  have hbox : box.Finite :=
    (Set.finite_Icc (-(K : ℤ)) (K : ℤ)).prod
      (Set.finite_Icc (-(K : ℤ)) (K : ℤ))
  apply hbox.subset
  rintro w ⟨n, rfl⟩
  have hA : A ≤ (K : ℝ) := le_trans (le_max_left A B) hK
  have hB : B ≤ (K : ℝ) := le_trans (le_max_right A B) hK
  have hbds := hbounds n
  have h1 := abs_le.mp (le_trans hbds.1 hA)
  have h2 := abs_le.mp (le_trans hbds.2 hB)
  change (-(K : ℤ) ≤ (quadraticLatticeCoords D q v n).1 ∧
      (quadraticLatticeCoords D q v n).1 ≤ (K : ℤ)) ∧
    (-(K : ℤ) ≤ (quadraticLatticeCoords D q v n).2 ∧
      (quadraticLatticeCoords D q v n).2 ≤ (K : ℤ))
  constructor
  · constructor
    · exact_mod_cast h1.1
    · exact_mod_cast h1.2
  · constructor
    · exact_mod_cast h2.1
    · exact_mod_cast h2.2

/-- Eventual periodicity of the state orbit itself. -/
def OrbitEventuallyPeriodic (beta x : ℝ) : Prop :=
  ∃ N p : ℕ, 0 < p ∧
    ∀ n, orbit beta x (N + n + p) = orbit beta x (N + n)

theorem state_repeat_implies_orbit_periodicity
    {beta x : ℝ} {N p : ℕ} (hp : 0 < p)
    (hrepeat : orbit beta x (N + p) = orbit beta x N) :
    OrbitEventuallyPeriodic beta x := by
  refine ⟨N, p, hp, ?_⟩
  intro n
  calc
    orbit beta x (N + n + p) = orbit beta x ((N + p) + n) := by
      rw [show N + n + p = (N + p) + n by omega]
    _ = orbit beta (orbit beta x (N + p)) n := orbit_add beta x (N + p) n
    _ = orbit beta (orbit beta x N) n := by rw [hrepeat]
    _ = orbit beta x (N + n) := (orbit_add beta x N n).symm

theorem quadraticLattice_state_repeat
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval D.beta
      (quadraticLatticeValue D.beta q v)) :
    ∃ N p : ℕ, 0 < p ∧
      orbit D.beta (quadraticLatticeValue D.beta q v) (N + p) =
        orbit D.beta (quadraticLatticeValue D.beta q v) N := by
  let S := Set.range (quadraticLatticeCoords D q v)
  have hS : S.Finite := quadraticLatticeCoords_finite_range D hq v hx
  let f : ℕ → S := fun n => ⟨quadraticLatticeCoords D q v n, ⟨n, rfl⟩⟩
  let _ : Finite S := hS
  obtain ⟨i, j, hij, heq⟩ := Finite.exists_ne_map_eq_of_infinite f
  have hcoords : quadraticLatticeCoords D q v i =
      quadraticLatticeCoords D q v j := congrArg Subtype.val heq
  rcases lt_or_gt_of_ne hij with hij | hji
  · refine ⟨i, j - i, Nat.sub_pos_of_lt hij, ?_⟩
    have hadd : i + (j - i) = j := Nat.add_sub_of_le hij.le
    rw [hadd, ← quadraticLatticeCoords_beta_value D hq v i,
      ← quadraticLatticeCoords_beta_value D hq v j, hcoords]
  · refine ⟨j, i - j, Nat.sub_pos_of_lt hji, ?_⟩
    have hadd : j + (i - j) = i := Nat.add_sub_of_le hji.le
    rw [hadd, ← quadraticLatticeCoords_beta_value D hq v i,
      ← quadraticLatticeCoords_beta_value D hq v j, hcoords]

/-- Generic L6 capstone: a point in a fixed-denominator quadratic lattice has
eventually periodic state and digit orbits. -/
theorem quadraticLattice_eventuallyPeriodic
    (D : QuadraticLatticeData) {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval D.beta
      (quadraticLatticeValue D.beta q v)) :
    OrbitEventuallyPeriodic D.beta (quadraticLatticeValue D.beta q v) ∧
      EventuallyPeriodic
        (orbitStream D.beta (quadraticLatticeValue D.beta q v)) := by
  obtain ⟨N, p, hp, hrepeat⟩ := quadraticLattice_state_repeat D hq v hx
  exact ⟨state_repeat_implies_orbit_periodicity hp hrepeat,
    state_repeat_implies_digit_periodicity hp hrepeat⟩

def sqrtTwoLatticeData : QuadraticLatticeData where
  beta := sqrtTwoBase
  conjugate := 1 - Real.sqrt 2
  trace := 2
  norm := -1
  beta_mem := sqrtTwoBase_between
  conjugate_abs_lt_one := by
    rw [abs_of_nonpos (by linarith [sqrt_two_bounds.1])]
    linarith [sqrt_two_bounds.2]
  beta_ne_conjugate := by
    unfold sqrtTwoBase
    linarith [sqrt_two_bounds.1]
  beta_polynomial := by simpa [sub_eq_add_neg] using sqrtTwoBase_polynomial
  conjugate_polynomial := by
    norm_num
    nlinarith [sqrt_two_sq]

def sqrtThreeLatticeData : QuadraticLatticeData where
  beta := sqrtThreeBase
  conjugate := 1 - Real.sqrt 3
  trace := 2
  norm := -2
  beta_mem := sqrtThreeBase_between
  conjugate_abs_lt_one := by
    rw [abs_of_nonpos (by linarith [sqrt_three_bounds.1])]
    linarith [sqrt_three_bounds.2]
  beta_ne_conjugate := by
    unfold sqrtThreeBase
    linarith [sqrt_three_bounds.1]
  beta_polynomial := by simpa [sub_eq_add_neg] using sqrtThreeBase_polynomial
  conjugate_polynomial := by
    norm_num
    nlinarith [sqrt_three_sq]

def goldenLatticeData : QuadraticLatticeData where
  beta := goldenBase
  conjugate := (3 - Real.sqrt 5) / 2
  trace := 3
  norm := 1
  beta_mem := goldenBase_between
  conjugate_abs_lt_one := by
    rw [abs_of_nonneg (by linarith [sqrt_five_bounds.2])]
    linarith [sqrt_five_bounds.1]
  beta_ne_conjugate := by
    unfold goldenBase
    linarith [sqrt_five_bounds.1]
  beta_polynomial := by simpa using goldenBase_polynomial
  conjugate_polynomial := by
    norm_num
    nlinarith [sqrt_five_sq]

theorem sqrtTwo_lattice_eventuallyPeriodic
    {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval sqrtTwoBase
      (quadraticLatticeValue sqrtTwoBase q v)) :
    OrbitEventuallyPeriodic sqrtTwoBase
        (quadraticLatticeValue sqrtTwoBase q v) ∧
      EventuallyPeriodic
        (orbitStream sqrtTwoBase (quadraticLatticeValue sqrtTwoBase q v)) := by
  simpa [sqrtTwoLatticeData] using
    quadraticLattice_eventuallyPeriodic sqrtTwoLatticeData hq v hx

theorem sqrtThree_lattice_eventuallyPeriodic
    {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval sqrtThreeBase
      (quadraticLatticeValue sqrtThreeBase q v)) :
    OrbitEventuallyPeriodic sqrtThreeBase
        (quadraticLatticeValue sqrtThreeBase q v) ∧
      EventuallyPeriodic
        (orbitStream sqrtThreeBase (quadraticLatticeValue sqrtThreeBase q v)) := by
  simpa [sqrtThreeLatticeData] using
    quadraticLattice_eventuallyPeriodic sqrtThreeLatticeData hq v hx

theorem golden_lattice_eventuallyPeriodic
    {q : ℕ} (hq : 0 < q) (v : ℤ × ℤ)
    (hx : InFundamentalInterval goldenBase
      (quadraticLatticeValue goldenBase q v)) :
    OrbitEventuallyPeriodic goldenBase
        (quadraticLatticeValue goldenBase q v) ∧
      EventuallyPeriodic
        (orbitStream goldenBase (quadraticLatticeValue goldenBase q v)) := by
  simpa [goldenLatticeData] using
    quadraticLattice_eventuallyPeriodic goldenLatticeData hq v hx

end

end CNRSProblem1
